//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTienda.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntidadesLibreria : DbContext
    {
        public EntidadesLibreria()
            : base("name=EntidadesLibreria")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TFACTURA> TFACTURA { get; set; }
        public virtual DbSet<TPRODUCTOS> TPRODUCTOS { get; set; }
        public virtual DbSet<TRUCCLIENTE> TRUCCLIENTE { get; set; }
        public virtual DbSet<TDESCUENTOS> TDESCUENTOS { get; set; }
    }
}
