//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTienda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TFACTURA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TFACTURA()
        {
            this.TDESCUENTOS = new HashSet<TDESCUENTOS>();
        }
    
        public int CODFACTURA { get; set; }
        public int RUC { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDESCUENTOS> TDESCUENTOS { get; set; }
        public virtual TRUCCLIENTE TRUCCLIENTE { get; set; }
    }
}
