//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTienda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPRODUCTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TPRODUCTOS()
        {
            this.TDESCUENTOS = new HashSet<TDESCUENTOS>();
        }
    
        public int CODPRODUCTO { get; set; }
        public string PRODUCTO { get; set; }
        public Nullable<decimal> VALOR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDESCUENTOS> TDESCUENTOS { get; set; }
    }
}
