//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTienda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRUCCLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRUCCLIENTE()
        {
            this.TFACTURA = new HashSet<TFACTURA>();
        }
    
        public int RUC { get; set; }
        public string NOMBRECLIENTE { get; set; }
        public string CIUDAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TFACTURA> TFACTURA { get; set; }
    }
}
